class ConnectionError(Exception):
    def __init__(self):
        self.super()
